- book/01-introduction/sections/01-why-atom.asc
Noticed this while reading the docs, and seems to the only link formatted this way.
> Fix oddly camel cased GitHub URL

- book/03-hacking-atom/sections/02-a-basic-package.asc
Change `activationEvents` to `activationCommands` and update the description to match current behavior.
> Fix activationEvents -> activationCommands

- book/03-hacking-atom/sections/A01-debugging.asc
Broken because there was a space between the URL and the text, and one link was pointing to the old docs site.
> Fix a few links in the debugging guide

- book/03-hacking-atom/sections/03-modify-buffer.asc
This is part 2 of fixing https://github.com/atom/ascii-art/issues/2, you can see part 1 here: https://github.com/atom/ascii-art/pull/3.
There was a bunch of small things causing problems for users following the guide step-by-step, and the guide didn't match exactly what the package generator created and what the demo package in https://github.com/atom/ascii-art looked like. 
/cc @kiwitotoro @erikweibust @pbrianmackey who were discussing problems over in https://github.com/atom/ascii-art/issues/2.
> Update guide for ascii-art package

- book/02-using-atom/sections/01-packages-themes.asc
The parenthesis was being included in the link.
> invalid href to `atom/settings-view` at `01-packages-themes.asc`

- book/03-hacking-atom/sections/02-a-basic-package.asc
Old description/summary mentioned that you should use `minor` when removing a feature, and that's incorrect.
> updated semver summary, closes #29

- book/02-using-atom/sections/06-customizing.asc
Added a note stating that individual invisible character types can be turned off with a boolean `false` (per the config schema).
The only other option to disable individual characters is to set them to an empty string (`''`), however due to a bug with handling the empty default values, configuration for `invisibles` will be [reset every time the Settings tab is opened](https://github.com/atom/settings-view/issues/237)!
It's best to mention that the "correct" way for disabling certain invisibles is with a boolean.
> Clarification for invisible characters

- book/04-behind-atom/sections/06-services-api.asc
Editing the title of the Services API section.
> Add 'other' back to title

- outline.txt
I'm not sure if the `outline.txt` is the plan-of-record anymore, but I figured this should be updated if it was still being used to record ideas.
> Update references to atom-shell to Electron

- book/01-introduction/sections/02-installing.asc
This closes https://github.com/atom/docs/issues/55 by adding the [Behind a firewall](https://github.com/atom/apm#behind-a-firewall) section from the apm README to the "Installing Atom" chapter of the Flight Manual.
> Add docs on setting up a proxy

- outline.md
Makes the book outline a little prettier (and lets us use things like TODO lists) :stuck_out_tongue_closed_eyes: 
/cc @atom/issue-triage
> Convert book outline to Markdown

- book/04-behind-atom/sections/07-maintaining-your-packages.asc
Adapted from https://github.com/atom/atom/blob/master/docs/apm-rest-api.md#renaming-a-package
/cc @atom/issue-triage
> Add sub-section on renaming packages

- book/01-introduction/sections/03-basics.asc
- book/02-using-atom/1-using-atom.asc
- book/02-using-atom/sections/01-packages-themes.asc
- book/02-using-atom/sections/02-text.asc
- book/02-using-atom/sections/03-interface.asc
- book/02-using-atom/sections/04-git-markdown.asc
- book/02-using-atom/sections/05-writing.asc
While going through Atom's Flight Manual, I noticed some small grammar mistakes here and there. This PR contains corrections for them.
> Flight Manual grammar documentation fixes

- book/02-using-atom/sections/06-customizing.asc
Found this while browsing the docs for the first time. The current code example throws a deprecation warning and does nothing.  Enjoying Atom overall though, congratulations :tada:.
> Update css selector to ::shadow for .cursor

- book/03-hacking-atom/sections/03-a-basic-package.asc
This PR documents `activationHooks`, a new key in `package.json`. See also: https://github.com/atom/atom/pull/7638
/cc @thedaniel @nathansobo
> :abc: Document activationHooks

- book/01-introduction/sections/03-basics.asc
The keystroke on Mac for command window:save-all should be `alt-cmd-s` instead of `ctrl-shift-S`.
> Correct save all opened files key shortcut

- book/01-introduction/1-introduction.asc
- book/01-introduction/sections/03-basics.asc
Fix typos in chapter 1 of the Atom Flight Manual in `1-introduction.asc` and `03-basics.asc`.
> Fix typos in Atom Flight Manual chapter 1

- book/01-introduction/sections/02-installing.asc
- book/01-introduction/sections/03-basics.asc
Explain how Atom on OS X attempts to install the `atom` and `apm`
commands in `02-installing.asc` and link to this explanation in
`03-basics.asc`. Resolves #96.
> Explain installation of atom and apm on OS X

- book/01-introduction/sections/02-installing.asc
Move the location of the link target `[[_installing_atom_on_mac]]` in `02-installing.asc`.
The current location of `[[_installing_atom_on_mac]]` works when the book is built locally and viewed as a single web page (`atom.html`) but is broken when the book's HTML is split up into files on https://atom.io/docs/v1.0.2/. The new location in this commit seems to produce the correct HTML that should fix the problem.
Also fix a spelling error.
> Fix broken link and spelling error in Flight Manual chapter 1

- book/02-using-atom/sections/02-text.asc
- book/02-using-atom/sections/06-customizing.asc
Closes https://github.com/atom/docs/issues/43
Closes #102
Refs https://github.com/atom/atom/issues/2695#issuecomment-125680992
/cc @atom/issue-triage
> Add CSON primer

- book/01-introduction/sections/03-basics.asc
> Improve 'opening directories' (multi-platform) wording in docs' introduction

- book/01-introduction/sections/03-basics.asc
- book/03-hacking-atom/sections/06-iconography.asc
- book/A-upgrading/sections/package.asc
This fixes up a few warnings that are currently produced by the build process.
Warnings fixed:
```
$ bundle exec rake book:build
Converting to HTML...
asciidoctor: WARNING: book/01-introduction/sections/03-basics.asc: line 108: invalid style for listing block: script
asciidoctor: WARNING: book/03-hacking-atom/sections/06-iconography.asc: line 5: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: book/03-hacking-atom/sections/06-iconography.asc: line 21: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: book/03-hacking-atom/sections/06-iconography.asc: line 25: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: book/A-upgrading/sections/package.asc: line 449: list item index: expected 2, got 1 …
```
> Fix some asciidoctor warnings

- book/03-hacking-atom/sections/A01-debugging.asc
cc @kevinsawicki for :eyes: because you added this in https://github.com/atom/atom/pull/6543 and I think it would be neat to have it documented here so that we can link to it.
> Add note on --profile-startup flag to debugging guide

- book/03-hacking-atom/sections/A02-writing-specs.asc
Refs https://github.com/atom/atom/pull/8968
We may want to wait to merge this until some community members experiment with the new API a bit.
> Add custom test runner docs

- .travis.yml
It seems atom/docs has been failing on Travis for quite a while. This should fix it.
> Add .travis.yml to fix build break

- book/02-using-atom/sections/06-customizing.asc
Because it can be hard to tell what other, more-specific selector is
overriding a user customization. In my case, it was a platform-specific
selector.
> Add sentence on Keybindings Resolver view.

- book/03-hacking-atom/1-hacking-atom.asc
Added a short summary to chapter 3, because the [current page](https://atom.io/docs/v1.5.3/hacking-atom-summary) was still empty. This will look a lot better and give more info.
> Add summary chapter 3

- content/hacking-atom/sections/package-word-count.asciidoc
The list of known activation hooks was previously confusing because the list had only one item, and when rendered showed up as a bullet point in the same level list of `package.json` properties.
The only hook I could find any mention of was the one that was already there, so I assume it's the only one. Changed the wording to indicate that.
Also made the use of e.g. clearer w/ parentheses.
> Clearer list of activationHooks

- CONTRIBUTING.md
- assets/stylesheets/app/_flight_manual.scss
- layouts/article.html
- layouts/includes/bottom_bar.html
Several potential contributors [had trouble finding this repository](https://github.com/atom/flight-manual.atom.io/issues/176). We discussed some possible changes to make it easier to go from *viewing* the Atom docs to *proposing edits* to them. 
- Add a "contribute!" link to the bottom bar of each docs page.
- Add explanatory links to the overview of CONTRIBUTING.md
Please be kind O:-)
> Add contributing links and "improve this page" links

- content/hacking-atom/index.asciidoc
See http://asciidoctor.org/docs/migration/#migration-cheatsheet for details. Asciidoctor is now using the modern syntax everywhere by default (unless you explicitly enable compat-mode).
> Switch to modern smart quote syntax

- content/hacking-atom/sections/writing-specs.asciidoc
Fixes https://github.com/atom/docs/issues/143
I tried to match the style of jasmine's documentation on its matchers.
> Add documentation on custom matchers for specs

- content/behind-atom/sections/interacting-with-other-packages-via-services.asciidoc
Found a small syntax error in [Chapter 4: Interacting With Other Packages Via Services](http://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/):
> Fix typo in service doc

- content/hacking-atom/sections/package-word-count.asciidoc
Basically someone asked on the forum how to publish a package, but:
- The table of content don't contain the word "publish".
- This page show up in search, I first dismissed it because I interpreted  "Package: Word count" as I would have interpreted "Package: Fuzzy Finder", that is: an explanation of some bundled package in atom.
On earlier version of atom flight manual this link pointed to somewhere.
https://atom.io/docs/v0.94.0/publishing-a-package 
I find this structure very descriptive to the goal intended. Reading the link explain it. 
This description power is somewhat lost using
http://flight-manual.atom.io/hacking-atom/sections/package-word-count
---
I'll end with the fact I'm not a native English speaker, so I don't expect my title to be retained, simply want to raise awareness …
> Update descriptive title for example package

- content/using-atom/sections/moving-in-atom.asciidoc
Now columns are consistent, all the arrow-key bindings are on the left side.
I'm fine with the Emacs bindings first, just want consistency.
> swap order of keybindings, to keep things consistent

- content/behind-atom/sections/interacting-with-other-packages-via-services.asciidoc
Fixes #202 
Each page requires a title (that matches) in order for the table of contents to render properly.
> Add title to page

- content/using-atom/sections/basic-customization.asciidoc
This PR updates the "Style Tweaks" section
- Make it more clear that CSS only also works in Less files.
- Add sub-section about styling the text editor with `::shadow`. Closes #56
> Update Style Tweaks

- content/using-atom/sections/snippets.asciidoc
documents this feature atom/snippets#133
> add multiple cursor documentation

- README.md
- outline.md
In `README.md` the link to the licence used the file extension `.asc`, rather than the new `.asciidoc` extension implemented in @54e76320c6d599cd63b11d46acdf251c1b298228.
In `outline.md`, the introduction referenced files with a `.asc` extension instead of files with a `.asciidoc` extension. What I've done here is simply fix both of these issues, both files now use `.asciidoc`.
> Change .asc to .asciidoc in README.md and outline.md

- content/using-atom/sections/writing-in-atom.md
> Remove spell check dictionary switcher verbiage

- Gemfile
- Gemfile.lock
- content/using-atom/sections/moving-in-atom.md
Fixes #205
Since the version of nanoc we're currently using works fine for our purposes, we'll stick with v4.1.x for now until gjtorikian/nanoc-conref-fs#5 is fixed.
> Don't upgrade to nanoc v4.2

- assets/stylesheets/app/_index.scss
Added an extra guard to ensure that the TOC style doesn't bleed over into the footer.
/cc @simurai Not sure if this is the best way to do this, though it appears effective. 💭 ?
> Fix oversized footer on root page

- content/using-atom/sections/snippets.md
Wanted to make it a bit more obvious how to create multiple snippets per scope for others who are as unfamiliar with CSON as I am. The vague warning (and link) to *Configuring with CSON* didn't help either, so after some trial and error, I figured this out. Shortly thereafter found the *Configuring with CSON* section that confirmed what I had come across.
> Added example of multiple snippets per scope.

- assets/javascripts/platform-nav.js
- assets/stylesheets/app/_flight_manual.scss
- assets/stylesheets/app/_platform_nav.scss
- layouts/article.html
- layouts/includes/platform-nav.html
This
- removes the article title (already shown)
- moves the platform-nav next to the "Improve this page" link
- restyles the platform-nav
Before | After
--- | ---
Closes #249
> Restyle platform-nav

- content/hacking-atom/sections/creating-a-theme.md
- content/hacking-atom/sections/package-word-count.md
- content/hacking-atom/sections/publishing.md
- data/toc.yml
This PR moves the [Publishing](http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#publishing) section that is part of the Word Count example to its own page.
- Easier to discover for something that people might try to find regularly, not just when creating their first package.
- Less confusing when linking from "Creating a theme".
Closes #247
> Move the Publishing section to its own page

- content/search.json
Markdown files are currently left out when building `search.json` resulting in #253.
This adds them again and brings back search functionality.
> Include markdown files into search.json

- content/using-atom/sections/version-control-in-atom.md
Until https://github.com/atom/atom/issues/2203 is resolved Git integration only works if the project root contains the repository. This took me a couple of hours to figure out because all the docs seem to say Git integration is built-in and should just work.
> Added note about Git repository root

- assets/javascripts/platform-nav.js
Fixes #264 
I tested this and it appears to work in all cases.
> Remove 'all' from list of platform-specific sections

- content/hacking-atom/sections/cross-platform-compatibility.md
> Windows requires double quotes in path with spaces

- content/using-atom/sections/basic-customization.md
In `basic-customization.md`, a blank line seems to be missing between paragraphs. This is how it currently looks:
> Add a blank line to separate paragraphs

- content/using-atom/sections/basic-customization.md
There are currently a few missing settings from this list, and one removed. The current list can be found at https://github.com/atom/settings-view/blob/master/lib/settings-panel.coffee#L17. The removed setting has a PR open here: https://github.com/atom/settings-view/issues/873.
I also put the items in order of appearance in the settings view (alphabetic).
> Update language-scoped settings list

- content/using-atom/sections/basic-customization.md
The keybinding appears to be Ctrl+Shift+I for Windows also, not Alt+Ctrl+I.
> Change keybinding for Developer Tools on Windows

- content/using-atom/sections/snippets.md
- content/using-atom/sections/writing-in-atom.md
The default keybinding was removed in atom/snippets.  Ref: atom/snippets@690d4fd
> Remove alt-shift-s reference

- content/behind-atom/sections/developing-node-modules.md
If the user has cloned Atom in the non-default location this will help to be aware that they have to set an environment variable in order for `atom --dev` work correctly.
> mention ATOM_DEV_RESOURCE_PATH when using custom location

- content/using-atom/sections/atom-packages.md
`git-grep` is broken for more than a year: https://github.com/mizchi/atom-git-grep/issues/13 Replaced it by the first hit of the current `search coffee`.
> Update packages example at the bottom of "Atom packages"

- content/getting-started/sections/installing-atom.md
Documents the enhancements in https://github.com/atom/atom/pull/13426
Also cleaned up the Linux section (clearer headings, removed 'download' as the package manager examples only install, not download)
> Document enhancements to portable mode and clarify section

- content/hacking-atom/sections/writing-specs.md
This documents the options parameter for `waitsForPromise` at https://github.com/atom/atom/blob/master/spec/spec-helper.coffee#L237
> add waitsForPromise option parameter

- content/hacking-atom/sections/package-active-editor-info.md
- data/toc.yml
This tutorial covers openers, `atom.workspace.toggle()`, constraining item locations (via `getDefaultLocation()` and `getAllowedLocations()`) and item serialization.
**It goes with atom/atom#13977, so it shouldn't be merged until that's landed and released.** (Or we've updated it with an "As of Atom 1.X" disclaimer.)
I've got [a corresponding repo](https://github.com/matthewwithanm/active-editor-info) which I can transfer over to the Atom org whenever.
cc @nathansobo @maxbrunsfeld @lee-dohm
> Add a new package tutorial that covers workspace items

- content/hacking-atom/sections/package-word-count.md
Let's use the apostrophe correctly in the manual.
> Fixed a typo in package-word-count.md

- content/using-atom/sections/basic-customization.md
lineHeight is a configuration option for the editor, but was not documented in the Flight Manual.
> Document lineHeight config key in editor options

- content/hacking-atom/sections/package-active-editor-info.md
🚨 **Do not merge until v1.17 reaches the Stable channel.** 🚨 
Removes the beta warning block from the tutorial added in #332.
> Remove the beta warning for the tutorial dependent on v1.17

- content/hacking-atom/sections/publishing.md
(This is a fixed version of #351.)
Semantic versioning covers the exposed interfaces of a package, not whether the developer perceives it as a 'bugfix' or otherwise. Therefore, the original explanation of `minor` vs. `patch` was incorrect.
> Fix semantic versioning explanation

- content/hacking-atom/sections/debugging.md
When merged this pull request will
- fix a keybind error for opening the developer tools in atom
- the keybind is `shift + ctrl + I` instead of `alt + ctrl + I`
- I'm unaware of mac but I'm quite sure that it should be shift too there
> Fixed developer tools keybinds

- content/using-atom/sections/editing-and-deleting-text.md
Updated the keybinding to select text inside the current brackets, as it has been updated in the package bracket-matcher for windows and linux.
> fix: keybinding to select text inside brackets

- content/hacking-atom/sections/debugging.md
The macOS key combination described in the flight manual is Cmd+Shift+I. However, the default is Alt+Cmd+I.
> Fix Toggle Developer Tools macOS key combination

- content/getting-started/sections/installing-atom.md
Since we no longer offer this installation package, we should remove the instructions from the manual.
> Remove MSI installer instructions

- Rakefile
Prior to this change, the build was [failing](https://travis-ci.org/atom/flight-manual.atom.io/builds/265717625#L332) as follows:
```
- ./output/upgrading-to-1-0-apis/sections/upgrading-your-syntax-theme/index.html
*  External link http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201#toc-style-host failed: 301 Peer certificate cannot be authenticated with given CA certificates
- ./output/upgrading-to-1-0-apis/sections/upgrading-your-ui-theme-or-package-selectors/index.html
*  External link http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom failed: 301 Peer certificate cannot be authenticated with given CA certificates
*  External link http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201#toc-style-cat-hat failed: 301 Peer certificate cannot be …
```
> Fix CI failure: "301 Peer certificate cannot be authenticated"

- .travis.yml
Prior to this change, the [CI build was suffering](https://travis-ci.org/atom/flight-manual.atom.io/builds/277092727) from the following 2 failures:
```
- ./output/hacking-atom/sections/package-active-editor-info/index.html
*  External link https://nuclide.io failed: response code 0 means something's wrong.
It's possible libcurl couldn't connect to the server or perhaps the request timed out.
Sometimes, making too many requests at once also breaks things.
Either way, the return message (if any) from the server is: SSL connect error
- ./output/using-atom/sections/moving-in-atom/index.html
*  External link https://ctags.io failed: response code 0 means something's wrong.
It's possible libcurl couldn't connect to the server or perhaps the request timed out.
Sometimes, making too many …
```
> Fix Travis CI failures related to SSL certificate issues

- content/behind-atom/sections/developing-node-modules.md
Some node modules, for example `atom-keymap`, `keyboard-layout` and `node-pathwatcher` requires `apm rebuild` to be run in the Atom directory on Windows. This PR changes the steps so `apm rebuild` is always run from the Atom directory.
/cc: @50Wliu
> Fix the steps for developing node modules

- content/hacking-atom/sections/package-modifying-text.md
The shortcut for windows, window reload was
Alt+Ctrl+R
but needs to be updated to
Ctrl+Shift+F5
> Update the windows reload shortcut

- content/hacking-atom/sections/creating-a-theme.md
The windows shortcut to open the developer tool was 
Alt+Ctrl+I
but needs to be
Ctrl+Shift+I
> Update windows shortcut to developer tool

- content/hacking-atom/sections/handling-uris.md
- data/toc.yml
Depends on https://github.com/atom/atom/pull/11399
[Rendered view](https://github.com/atom/flight-manual.atom.io/blob/mkt-add-docs-for-package-uri-handling/content/hacking-atom/sections/handling-uris.md)
> Add docs for URI handling

- content/behind-atom/sections/keymaps-in-depth.md
Even after reading the original Flight Manual section, "Forcing Chromium's Native Keystroke Handling", I didn't make the connection that a bug with not being able to use backspace or arrow keys inside an included component (which has an input field) was related.   Clarified this in a tip.
> Clarified backspace and arrow key issues with components and input field

- content/hacking-atom/sections/hacking-on-atom-core.md
It turns out that I flubbed the directory where `ATOM_DEV_RESOURCE_PATH` is supposed to point to :blush:
> Fix where ATOM_DEV_RESOURCE_PATH is supposed to point to

- content/hacking-atom/sections/publishing.md
This should fix the build errors occurring.
> Link to GitHub Help instead of broken Desktop guide link

- content/getting-started/sections/installing-atom.md
I've updated the Linux installation instructions to add steps for configuring package repositories for distributions using the .deb and .rpm formats.  Would love for @ungb to double-check the steps before we merge this just to make sure everything works correctly :)
> Add instructions for installing Atom using Linux package repos

- .travis.yml
- package.json
This change forces TravisCI to use Node.js 7 instead of the system-wide
install (Node.js 9) to avoid version compatibility issues with the
node-sass package.  node-sass has builds against specific Node.js versions
and can't be used with anything newer than Node.js 7 unless we upgrade
our node-sass dependency.
> Force TravisCI to use Node.js 7 to avoid node-sass compatibility error

- content/atom-server-side-apis/index.md
- content/atom-server-side-apis/sections/atom-package-server-api.md
- content/atom-server-side-apis/sections/atom-update-server-api.md
- data/toc.yml
Since the majority of Atom's documentation is here, the server API information was somewhat hard-to-find unless someone pointed you there. This resolves that problem.
> Relocate Atom's server API documentation to the Flight Manual

- README.md
- content/behind-atom/sections/keymaps-in-depth.md
- content/hacking-atom/sections/contributing-to-official-atom-packages.md
- content/hacking-atom/sections/converting-from-textmate.md
- content/hacking-atom/sections/creating-a-grammar.md
- content/hacking-atom/sections/hacking-on-atom-core.md
- content/hacking-atom/sections/iconography.md
- content/hacking-atom/sections/package-word-count.md
- content/hacking-atom/sections/publishing.md
- content/hacking-atom/sections/writing-specs.md
- content/shadow-dom/sections/removing-shadow-dom-styles.md
- content/upgrading-to-1-0-apis/sections/upgrading-your-package.md
- content/upgrading-to-1-0-apis/sections/upgrading-your-syntax-theme.md
- content/upgrading-to-1-0-apis/sections/upgrading-your-ui-theme-or-package-selectors.md
- content/using-atom/sections/atom-packages.md
- content/using-atom/sections/basic-customization.md
- content/using-atom/sections/find-and-replace.md
- content/using-atom/sections/moving-in-atom.md
- content/using-atom/sections/version-control-in-atom.md
- layouts/includes/bottom_bar.html
- layouts/includes/favicon.html
- layouts/includes/top_bar.html
- layouts/toc.html
- outline.md
URLs updated to use HTTPS protocol where appropriate to improve security and privacy.
> Update: HTTP -> HTTPS

- content/hacking-atom/sections/hacking-on-atom-core.md
As I suggested in https://github.com/atom/atom/issues/15368, this adds [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) to the build requirements as an option for Visual Studio. That title is also changed to C++ build tools, as it no longer only lists products directly related to Visual Studio.
> Add windows-build-tools to build instructions for Windows

- content/getting-started/sections/installing-atom.md
Instead of linking to the `atom/atom` repo, which then just links right back to the Flight Manual, link directly to the `Hacking on Atom Core` section of the Flight Manual.
> Link to the flight manual for building from source

- content/getting-started/sections/installing-atom.md
On Installing Atom page, there was anchor text directing visitors to the Atom releases page, but the hyperlink was missing. Also, this standardizes the anchor text between Mac and Windows sections.
> Add links to Atom releases page

- content/using-atom/sections/moving-in-atom.md
Atom has a few movement commands that exist, but aren't binded to any keyboard shortcut so they are hard to find unless you just know what exactly to type in the command palette.  This PR adds a section that makes it transparent what those commands (per platform), and tells people how to add a keyboard shortcut by adding a entry in keymaps.
Thanks @nathansobo for syncing up on this!  
Additional feedback would be awesome!  
/cc @lee-dohm @nathansobo @lukehefson @rsese
> Add new sections to discuss commands that have no keyboard shortcut by default

- content/hacking-atom/sections/creating-a-grammar.md
The first change is to add a link to the Oniguruma docs in the section about regular expressions. I feel this is important, to definitively point people to the right documentation.
The second change is to add a new section with links to other guides / useful information. My own guide was suggested to be included by @50Wliu, but I felt the others are all excellent as well (I know I depended on them). As I say in the short description, some links are present earlier in the guide. However, I feel it's good to have them all grouped together as well, to centralise everything.
I'm open to any suggested changes. I chose to use linked text instead of the raw links (in most cases) as I feel it helps explain the purpose of the link.
> Add a list of useful resources

- content/hacking-atom/sections/hacking-on-atom-core.md
Due to the change to install-application.js, the atom command may now be atom, atom-beta, or atom-dev depending upon the version of the source. Since -dev can be in the master branch, this note should be added for clarity.
> Note about modifications to the atom command

- content/hacking-atom/sections/debugging.md
This line feels like it should be somewhere else or just removed completely. This section is about checking the developer tools for errors. Not how you get stack traces to report issues.
* It does not specify what approach to use. Just `use this approach`
* The link is not working. Maybe it should be https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs
* You can already reproduce an error if you are checking the developer tools for errors
The line could be moved down to the bottom of this section and be reworded to say `"Include this information when opening an issue or question on discuss"`.
> Remove the use this approach line

- content/hacking-atom/sections/debugging.md
Add a GPU section in the debugging page by:
1. Adding back the changes from https://github.com/atom/flight-manual.atom.io/pull/402 which were accidentally removed in https://github.com/atom/flight-manual.atom.io/commit/f31fd8304eec58f2ec988c7f3eccb4a924c62fcd.
2. Adding some of @Arcanemagus's comment in https://github.com/atom/settings-view/issues/1050#issuecomment-376610112 since I think it provides good context for people that use `--disable-gpu`.
/cc @Arcanemagus for 👓
> Add (back) GPU debugging section

- content/behind-atom/sections/maintaining-your-packages.md
- content/hacking-atom/sections/hacking-on-atom-core.md
Some people insist on publishing packages manually. Give them the instructions to not shoot themselves in the foot but with a big danger sign so they know they're on their own.
Fixes #459 
/cc @Ben3eeE @Arcanemagus @rsese for extra :eyes:
> Add manual publishing process with big danger sign

- content/using-atom/sections/moving-in-atom.md
I updated "Additional Movement and Selection Commands" to make it clear these commands do not have default keybindings. This comes after checking intentions for the section in issue https://github.com/atom/flight-manual.atom.io/issues/465.
Comparing the Mac, Win32 and Linux lists against current keymaps, I found some key combinations that _are_ bound by default and removed them from the appropriate lists.
> Clarify movement and selection commands without default keybindings

- content/hacking-atom/sections/hacking-on-atom-core.md
This clarifies a lot of the confusion that I (and others) had on the #packages channel today.
Tangentially related, this package is really hard to hack on. Ruby 2.2.3 is almost 3 years old at this point. 2.5.1 is the latest. I was able to get it to bundle just using bundle directly, but script/bootstrap failed to install Nokogiri (lack of necessary headers?). Then I ran script/server, and got a different failure. I would include the logs for those here, but I tried to update npm and got a blue screen of death.
Therefore I haven't properly tested these changes, since I can't get the server to run for me. Shouldn't be any problems since it's just normal markdown.
> Added bullet about live reloading

- content/using-atom/sections/find-and-replace.md
Fixes #452
- Specified that Atom uses JavaScript regex syntax
- Added a link to JavaScript's documentation
> Add additional information about regex to find-and-replace.md

- content/hacking-atom/sections/hacking-on-atom-core.md
This PR updates the outdated link of VC2015 build tools in ```hacking-on-atom-core.md```, in order to fix the error thrown by HTML-Proofer. This should also fix the error returned in #472 .
> Fix broken link in hacking-on-atom-core.md

- content/hacking-atom/sections/creating-a-grammar.md
The javascript scope name changed from `javascript` to `source.js` in atom/language-javascript#591. The same change was done in atom/language-javascript@ea37ba47038b9e6f253a8a4b22cf7b611e79bf98.
> Use correct scope name for addInjectionPoint

- package-lock.json
- package.json
This remediates the 
vulnerability with `event-stream` outlined in https://github.com/dominictarr/event-stream/issues/116#issuecomment-440927400
`event-stream` is a dependency of `gulp-connect`.  By [pinning](https://renovatebot.com/docs/dependency-pinning/) the version of `gulp-connect`, now we are no longer including any version of `flatmap-stream` with this code.
I've seen some reports that only `flatmap-stream@0.1.1` contains the maliciously injected code, as part of the minified bundle.  `flight-manual.atom.io` was only ever running `flatmap-stream@0.1.0`, however it's better to be safe than sorry.
Downsides of pinning the version is that we won't get automatic upgrades when new versions of `gulp-connect` are released, and we'll have to manually upgrade. 
Run local version of server …
> pin version of gulp-connect

- content/behind-atom/sections/configuration-api.md
- content/behind-atom/sections/interacting-with-other-packages-via-services.md
- content/behind-atom/sections/keymaps-in-depth.md
- content/behind-atom/sections/scoped-settings-scopes-and-scope-descriptors.md
- content/behind-atom/sections/serialization-in-atom.md
- content/hacking-atom/sections/tools-of-the-trade.md
- content/hacking-atom/sections/writing-specs.md
This intentionally leaves alone:
* Examples having to do with configuration files
* The chapter on upgrading your package to the Atom v1.0 API (since anything pre-1.0 was in CoffeeScript anyway)
> Convert CoffeeScript code examples to JavaScript

- nanoc.yaml
Noticed the CI failure in https://github.com/atom/flight-manual.atom.io/pull/513 was the link checker finding broken emoji links:
```
Checking 227 external links...
Ran on 67 files!
- ./output/hacking-atom/sections/creating-a-theme/index.html
*  External link https://a248.e.akamai.net/assets.github.com/images/icons/emoji/unicode/1f389.png failed: 404 No error
- ./output/hacking-atom/sections/debugging/index.html
*  External link https://a248.e.akamai.net/assets.github.com/images/icons/emoji/unicode/1f6a8.png failed: 404 No error
- ./output/hacking-atom/sections/package-word-count/index.html
*  External link https://a248.e.akamai.net/assets.github.com/images/icons/emoji/unicode/1f600.png failed: 404 No error
- ./output/using-atom/sections/snippets/index.html
*  External link …
```
> Fix broken emoji URLs

- content/getting-started/sections/installing-atom.md
A couple of small updates to https://flight-manual.atom.io/getting-started/sections/installing-atom/#updating-atom:
* Miscommunication on my part about which sentence to remove in https://github.com/atom/flight-manual.atom.io/pull/513#discussion_r279132977
* Flesh out the section on updating on Linux a tiny bit
> "Updating Atom" tweaks

- content/hacking-atom/sections/hacking-on-atom-core.md
calling `script/bootstrap` in command line on Windows displays an error:
```
'script' is not recognized as an internal or external command,
operable program or batch file.
```
The solution is to use backslash instead of forward slash `script\bootstrap`
> fix calling bootstrap on windows

- Gemfile.lock
#541 changed `Gemfile.lock`'s bundler version from 1.16.3 to 2.0.2. Our CI build was fine with that change, but [publisher](https://github.com/gjtorikian/publisher) seems to use bundler 1.x, so publishing failed as seen in https://github.com/atom/flight-manual.atom.io/issues/553.
This pull request restores the use of bundler 1.16.3, and I anticipate that this will fix #553.
> ⬇️ bundler@1.16.3

- content/behind-atom/sections/keymaps-in-depth.md
RIP template links.
Fixes https://github.com/atom/atom/issues/19855
Changes the function kind so that the context of `this` is now `TextEditorElement` and `this.getModel()` works. Also changed the following snippet to use `this.getModel()` as well.
Semicolons introduced for consistency with Atom code base (and the other snippets in here I came across).
`TextEditorElement` is [undocumented](https://github.com/atom/atom/pull/13753). Technically could replace `this.getModel()` with `atom.workspace.getActiveTextEditor()`, to avoid an undocumented method call. However, getModel feels more correct in terms of linking the event to the right editor; it is possible for `atom.workspace.getActiveTextEditor()` to return a different editor, or none at all, whereas we can (probably) safely assume …
> Fix `this` context in JS snippets & increase consistency

- content/hacking-atom/sections/package-word-count.md
Sometimes `your-name-word-count` was used and sometimes `wordcount` as reference of the package name. I think its better to stick to only one of them for better readabilty.
Not applicable
> Avoid mixing your-name-word-count with wordcount

- content/hacking-atom/sections/hacking-on-atom-core.md
These two urls are redirecting to a new tracker on chromium, updating it to stay up to date and unblock the CI
> Update node gyp bug tracker URL

- content/faq/sections/what-platforms-does-atom-run-on.md
According to [this](https://github.com/electron/electron/blob/v6.1.12/docs/tutorial/support.md), electron support 10.10 (Yosemite) as the minimum OS X version
> Deprecate OS X 10.10 support to match electron

- content/hacking-atom/sections/hacking-on-atom-core.md
* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
Information on required Visual Studio versions and Python versions were out of date, considering that we use newer `node-gyp` now.
See: https://github.com/nodejs/node-gyp/tree/v5.x/#installation for a more up-to-date reference on the required Visual Studio and Python versions, and other miscellaneous requirements of `node-gyp`.
I updated "Hacking on Atom Core" …
> Hacking on Atom Core: Update build requirements to be accurate

- content/getting-started/sections/installing-atom.md
The current setup involves running `dpkg -i` to install the `.deb` file, followed by `apt-get -f` to install dependencies.
This can be combined into a single step by just using `sudo apt install ./atom-amd64.deb`, which will install both the Atom package and dependencies in one command.
> Updated installation command for .deb package
