atom/flight-manual.atom.io

- book/01-introduction/sections/02-installing.asc
No more Chocolatey. Also it auto updates :heart:
> docs(windows) atom on windows is just as awesome as the mac version

- book/01-introduction/sections/03-basics.asc
Changes reflect update in themes + syntax colors
> Changed theme and syntax color details

- book/02-using-atom/sections/06-customizing.asc
- book/03-hacking-atom/sections/01-tools.asc
> Rename LESS to Less

- book/03-hacking-atom/sections/02-a-basic-package.asc
> update example at chapter 3.2 due to source code change

- book/03-hacking-atom/sections/A02-writing-specs.asc
> Fix link in 3.6 Writing Specs

- book/01-introduction/sections/03-basics.asc
- book/02-using-atom/sections/02-text.asc
> Add docs for multi-folder projects

- book/A-upgrading/sections/ui-theme.asc
Also changed it to highlight the entire style block.
> Fix broken link

- book/02-using-atom/sections/02-text.asc
Fixes https://github.com/atom/docs/issues/30.
> Remove sentence about ~/.atom/snippets directory

- book/01-introduction/sections/03-basics.asc
This closes https://github.com/atom/docs/issues/53.
> Clarify shell commands installation

- book/04-behind-atom/1-behind-atom.asc
- book/04-behind-atom/sections/07-maintaining-your-packages.asc
I feel we need a section that covers slightly more advanced package ownership scenarios.
/cc @thedaniel
> Add section on less common package maintenance activities

- Gemfile.lock
- book/03-hacking-atom/1-hacking-atom.asc
- book/03-hacking-atom/sections/06-iconography.asc
- book/A-upgrading/sections/ui-theme.asc
This is missing from the docs. Added it.
> Added a page regarding icons.

- book/02-using-atom/1-using-atom.asc
- book/02-using-atom/sections/01-packages-themes.asc
- book/02-using-atom/sections/02-text.asc
- book/02-using-atom/sections/05-writing.asc
- book/02-using-atom/sections/06-customizing.asc
Fix typos, correct spelling and improve grammar and sentence structure in chapter 2 of the Atom Flight Manual.
> Update Atom Flight Manual chapter 2

- book/02-using-atom/sections/02-text.asc
Solving https://github.com/atom/snippets/issues/159
> Link to some used snippets

- book/02-using-atom/sections/02-text.asc
I am assuming the author meant to type "short" originally.
> Corrected typo within snippets section

- book/04-behind-atom/sections/01-config-api.asc
> Fix typo @ 'Configuration API' section

- book/03-hacking-atom/sections/A01-debugging.asc
> Fix typo @ 03-A01 (Debugging)

- README.md
> Fix Wrong License in Readme.md

- book/02-using-atom/sections/06-customizing.asc
> Add core.customFileTypes documentation

- book/03-hacking-atom/sections/02-init-file.asc
Fixes https://github.com/atom/atom.io/issues/46
> Fix link to Atom's global API

- book/03-hacking-atom/sections/03-a-basic-package.asc
To avoid confusion mentioned in #85, I've Added a waring note to "Package: Word Count" tutorial.
> Fix #85, Add a warning note to Word Count tutorial

- book/A-upgrading/sections/syntax.asc
> Fix a typo

- content/hacking-atom/sections/creating-a-theme.asciidoc
Update of #174 for the static site
Thanks to @houseoftech for the fix!
> Fix grammar in Creating A Theme

- content/getting-started/sections/atom-basics.asciidoc
This figure's title and content are not match.
> Fix figure title

- content/using-atom/sections/basic-customization.asciidoc
This clarifies the "search in the left panel". I think there used to be a search field in that panel, but later got moved into the Packages page.
Closes #195
> Clarify "left panel"

- content/getting-started/sections/installing-atom.asciidoc
Windows MSI installer package is coming soon as part of https://github.com/atom/atom/issues/11087
> Add section about the Windows MSI installer

- content/hacking-atom/sections/iconography.asciidoc
> Update Octicons link

- content/hacking-atom/sections/iconography.asciidoc
> Update styleguide link

- content/hacking-atom/sections/the-init-file.md
Quick fix to "The Init File". Not sure how this actually looks when generated - I had zero luck building the site (`rvm`/`rbenv` issues). Let me know if you'd like me to do anything else, thanks!
> fixing link to Package: Word Count

- content/getting-started/sections/installing-atom.md
Update #177 from @fusion809 to the new format and include @thedaniel's feedback.
> Add extra detail to Linux installation instructions

- content/using-atom/sections/pending-pane-items.asciidoc
- content/using-atom/sections/pending-pane-items.md
- data/toc.yml
Since we're getting questions about pending items and how to confirm them, I wanted to get this section into the manual.
> Add pending item information

- Gemfile
- Gemfile.lock
- Rakefile
- content/hacking-atom/sections/package-word-count.md
- lib/tasks/validate_article_title.rb
> Add title test

- Gemfile
- Gemfile.lock
- data/toc.yml
- layouts/includes/toc.html
- lib/chapter.rb
- lib/sections.rb
- lib/table_of_contents.rb
The Table of Contents system now allows for both chapters and appendices:
Also simplified the code around generating the table of contents.
> Convert to Chapter and Appendix system

- content/using-atom/sections/find-and-replace.md
(Surprisingly, globstar is not actually mentioned in the linked Wikipedia article)
> Note on "**" support in glob patterns

- content/using-atom/sections/moving-in-atom.md
Do not know how it on mac or windows
> In linux move to the top/bottom of the file - is Ctrl+home/end

- content/hacking-atom/sections/converting-from-textmate.md
Command-line use to convert language and theme from textmate
> Fix command-line

- content/using-atom/sections/writing-in-atom.md
- Change a phrase to not end with a preposition
- Use of Oxford comma apply throughout file
- Add comma to separate to independent clauses
> Update minor syntax issues in writing-in-atom.md

- content/behind-atom/sections/developing-node-modules.md
Fixes the instructions and adds more clarity around the process of successive updates.
> Fix Node modules instructions

- LICENSE.md
- content/upgrading-to-1-0-apis/sections/upgrading-your-package.md
- layouts/includes/top_bar.html
* Use https where possible
* Fix an outdated link
> Correct some links

- CONTRIBUTING.md
Also remove the reference to Asciidoc since it is no longer used.
> Simplify the wording

- content/behind-atom/sections/keymaps-in-depth.md
> Add documentation for the abort! keybinding directive

- gulpfile.js
> Fix broken favicon

- content/behind-atom/sections/serialization-in-atom.md
It says to return JSON, but it's unclear if one should return a serialized object (a string) or an object to be serialized.
> Clarify what to return in package deserialization

- content/behind-atom/sections/serialization-in-atom.md
Some documentation for the (relatively) new ability to register deserializers via `package.json`.
Released under CC0.
> Document registering deserializers in package.json

- content/getting-started/sections/atom-basics.md
FIxed a missing "in" in the "Atom Basics" section of the flight manual.
> Fixed a missing "in"

- content/behind-atom/sections/developing-node-modules.md
> Fix for review feedback

- content/hacking-atom/sections/publishing.md
> Use em tags to delineate a parameter in command-line blocks

- content/hacking-atom/sections/package-word-count.md
Added instructions to generate CoffeeScript package (used in the tutorial)
> Update default syntax in package generator

- content/behind-atom/sections/keymaps-in-depth.md
Document the process where people can update their own keystroke resolution without creating a package.
/cc @nathansobo
> Add information on addKeystrokeResolver

- content/behind-atom/sections/keymaps-in-depth.md
Refs https://github.com/atom/flight-manual.atom.io/pull/325#issuecomment-284122453
> Add check for event.type in the addKeystrokeResolver example

- content/hacking-atom/sections/package-word-count.md
Adds a simple note describing how to reload the window to see changes.
Fixes #330
> Adds note for reloading changes.

- content/behind-atom/sections/maintaining-your-packages.md
It appears that this is no longer needed thanks to @jasonrudolph :zap:.
/cc @lee-dohm for review
> Remove warning about unpublishing before deleting

- content/hacking-atom/sections/debugging.md
I added an article. Only "a" makes sense given the context, which is to check if the user is using the latest version.
> Grammar fix (add an article)

- content/hacking-atom/sections/contributing-to-official-atom-packages.md
Let's not encourage people to open issues on the Flight Manual :grin:.
> Change terminology from "here" to "atom/atom"

- content/using-atom/sections/snippets.md
the previously used text.md is outdated
> change language prefix to githubflavoured markdown

- content/getting-started/sections/installing-atom.md
As mentioned by @damieng in this PR: https://github.com/atom/about/pull/67
> Add note about auto-updating in portable mode

- content/behind-atom/sections/developing-node-modules.md
/cc @Ben3eeE we forgot to update the second command-line section :P.
Refs #390
> Fix Node module rebuilding after the initial steps

- content/hacking-atom/sections/hacking-on-atom-core.md
- data/toc.yml
> Add Hacking on Atom Core page

- content/hacking-atom/sections/creating-a-grammar.md
- data/toc.yml
The goal of this PR is to create a mini tutorial series on how to create a grammar package.  Given the scope of grammar packages, it'll probably be much longer and more in-depth than the existing package + theme tutorials.  Similar to the package tutorials, it'll be split into different sections of varying difficulty.
@DamnedScholar I wanted to get your feedback on this.
> [WIP] Add a grammar tutorial

- content/getting-started/sections/why-atom.md
> "really unique" is poor English

- content/hacking-atom/sections/debugging.md
Added useful debugging commands for GPU issues from #353 and explained them in the debugging section.
> Add useful debugging/rendering commands

- content/getting-started/sections/atom-basics.md
- content/getting-started/sections/why-atom.md
> A few minor revisions.

- content/getting-started/sections/installing-atom.md
'RedHat' -> 'Red Hat' and other minor fixes.
> Fix Red Hat install product names

- content/atom-server-side-apis/index.md
Forgot to add the header and figured adding the warning here too wouldn't hurt.
> Flesh out the index page to match others

- content/hacking-atom/sections/hacking-on-atom-core.md
@skylize is this better?
Fixes #435
> Reword ATOM_DEV_RESOURCE_PATH documentation

- content/hacking-atom/sections/hacking-on-atom-core.md
> Update recommended platform to Ubuntu 16.04

- content/hacking-atom/sections/hacking-on-atom-core.md
See https://github.com/atom/git-utils/issues/72
> Building on Mac requires python 2.7

- content/using-atom/sections/find-and-replace.md
This was oddly unintuitive to me. I followed the wikipedia link and read all about globs which was deceivingly unhelpful in helping me figure out how to search for multiple globs at a time, so I thought I'd add this tip for posterity (along with the other super helpful tips in this section!)
> Document search feature

- content/getting-started/sections/atom-basics.md
This PR completes the work started [here](https://github.com/atom/atom/pull/17569).
@lee-dohm please review
> Explain how to open a file at a certain line (and column)

- content/hacking-atom/sections/package-word-count.md
Deactivation advice mentioned in #508 corrected.
Fixes #508.
> Corrected deactivation advice

- content/behind-atom/sections/developing-node-modules.md
- content/behind-atom/sections/keymaps-in-depth.md
- content/hacking-atom/sections/creating-a-grammar.md
> Various fixes

- content/using-atom/sections/github-package.md
This PR removes a unnecessary word.
Fix grammar.
> Remove unnecessary word

- package-lock.json
- package.json
Upgrade to Node 8 so that we can use async/await. :pray:
> ⬆️ Upgrade to Node 8

- content/hacking-atom/sections/handling-uris.md
Add documentation for the URI to open files
Add documentation for the URI to open files
> Document core URI handler
